entryPoints:
  websecure:
    address: ":28080"
    forwardedHeaders:
      insecure: true
  traefik:
    address: ":28090"

api:
  dashboard: true
  insecure: true

providers:
  file:
    filename: "./bin/traefik/dynamic.yaml"
    watch: true


